# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8553b920fecbb4252b6e49cd8dfd6360ee1ecff64dba4519ba524f0e1f5d00efbce8962355a74739e7cf99de21f35c79b73a024717b2853eb6caed719b8416c

test:
  secret_key_base: 19d5ed4aa5d5ecb876794972e3cd59ae64917591d391b1f563ad9368d3af15ef8ce5a868a3260564f16e357171856a212883b5f87482fd6166f78200173ea14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
